# Generated by Django 3.2.5 on 2023-02-17 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('Google', 'Google'), ('Social', 'Social'), ('Referral', 'Referral'), ('Newsletter', 'Newsletter')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Nurturing', 'Nurturing'), ('Not Responding', 'Not Responding'), ('Converted', 'Converted')], max_length=50)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
