# Generated by Django 3.2.5 on 2023-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
